server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    import: optional:file:./db.yml
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite:./db.sqlite
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
    show-sql: true
